param(
  [string]$ServerUrl = '',
  [string]$AgentToken = '',
  [string]$ProxyApiKey = '',
  [string]$CodexHome = '',
  [string]$CodexBin = '',
  [string]$AllowedRoots = '',
  [string]$TaskName = 'Codex Mobile App Bridge',
  [switch]$RunNow,
  [switch]$NonInteractive
)

$ErrorActionPreference = 'Stop'

function Read-Value([string]$Prompt, [string]$Default = '', [switch]$Secret, [switch]$Required) {
  if ($NonInteractive) {
    if ($Required -and -not $Default) { throw "$Prompt is required." }
    return $Default
  }
  $suffix = if ($Default) { " [$Default]" } else { '' }
  if ($Secret) {
    $secure = Read-Host "$Prompt$suffix" -AsSecureString
    $bstr = [Runtime.InteropServices.Marshal]::SecureStringToBSTR($secure)
    try { $value = [Runtime.InteropServices.Marshal]::PtrToStringBSTR($bstr) } finally { [Runtime.InteropServices.Marshal]::ZeroFreeBSTR($bstr) }
  } else {
    $value = Read-Host "$Prompt$suffix"
  }
  if (-not $value -and $Default) { $value = $Default }
  if ($Required -and -not $value) { throw "$Prompt is required." }
  return $value
}

function Clean-InputValue([string]$Value) {
  return ($Value -replace '[\u200E\u200F\u202A-\u202E\u2066-\u2069]', '').Trim().Trim('"').Trim("'")
}

function Normalize-ServerUrl([string]$Value) {
  $clean = Clean-InputValue $Value
  $match = [regex]::Match($clean, 'https?://[^\s<>"]+')
  if ($match.Success) { $clean = $match.Value }
  $clean = $clean.TrimEnd('/', '.', ',', ';')
  $uri = $null
  if (-not [Uri]::TryCreate($clean, [UriKind]::Absolute, [ref]$uri)) {
    throw "Server URL is invalid. Paste only a URL like https://codex.example.com"
  }
  if ($uri.Scheme -notin @('http', 'https')) {
    throw "Server URL must start with http:// or https://"
  }
  return $clean
}

function Normalize-PathValue([string]$Value, [string]$Default = '') {
  $clean = Clean-InputValue $Value
  $matches = [regex]::Matches($clean, '([A-Za-z]:\\[^;\r\n]+|\\\\[^;\r\n]+)')
  if ($matches.Count -gt 0) {
    return ($matches | Select-Object -First 1).Value.Trim()
  }
  if ($Default) { return $Default }
  return $clean
}

function Normalize-PathListValue([string]$Value, [string]$Default = '') {
  $clean = Clean-InputValue $Value
  $matches = [regex]::Matches($clean, '([A-Za-z]:\\[^;\r\n]+|\\\\[^;\r\n]+)')
  if ($matches.Count -gt 0) {
    return (($matches | ForEach-Object { $_.Value.Trim() }) -join ';')
  }
  if ($Default) { return $Default }
  return $clean
}

function Find-CodexHome {
  foreach ($candidate in @(
    $env:CODEX_HOME,
    (Join-Path $env:USERPROFILE '.codex'),
    (Join-Path $env:LOCALAPPDATA 'OpenAI\Codex\codex-home')
  )) {
    if ($candidate -and (Test-Path -LiteralPath $candidate)) { return (Resolve-Path -LiteralPath $candidate).Path }
  }
  return ''
}

function Find-CodexBin {
  if ($env:TICMIRO_CODEX_BIN -and (Test-Path -LiteralPath $env:TICMIRO_CODEX_BIN)) {
    return (Resolve-Path -LiteralPath $env:TICMIRO_CODEX_BIN).Path
  }

  $DesktopBinRoot = Join-Path $env:LOCALAPPDATA 'OpenAI\Codex\bin'
  if (Test-Path -LiteralPath $DesktopBinRoot) {
    $DesktopBin = Get-ChildItem -LiteralPath $DesktopBinRoot -Directory -ErrorAction SilentlyContinue |
      ForEach-Object { Join-Path $_.FullName 'codex.exe' } |
      Where-Object { Test-Path -LiteralPath $_ } |
      Sort-Object { (Get-Item -LiteralPath $_).LastWriteTimeUtc } -Descending |
      Select-Object -First 1
    if ($DesktopBin) { return (Resolve-Path -LiteralPath $DesktopBin).Path }
  }

  foreach ($candidate in @(
    (Get-Command codex -ErrorAction SilentlyContinue | Select-Object -First 1 -ExpandProperty Source),
    (Join-Path $env:USERPROFILE '.local\bin\codex.exe'),
    (Join-Path $env:APPDATA 'npm\codex.cmd')
  )) {
    if ($candidate -and (Test-Path -LiteralPath $candidate)) { return (Resolve-Path -LiteralPath $candidate).Path }
  }
  return ''
}

$Root = Split-Path -Parent $PSScriptRoot
$StartScript = Join-Path $Root 'scripts\start-windows-bridge.ps1'
$EnvFile = Join-Path $Root '.env.local'

$ServerUrl = Normalize-ServerUrl (Read-Value 'Your server URL' $ServerUrl -Required)
$AgentToken = Read-Value 'Windows bridge token from server install' $AgentToken -Secret -Required
$ProxyApiKey = Read-Value 'Proxy API key from server install' $ProxyApiKey -Secret -Required
$DefaultCodexHome = $(if ($CodexHome) { $CodexHome } else { Find-CodexHome })
$CodexHome = Normalize-PathValue (Read-Value 'Codex home folder' $DefaultCodexHome -Required) $DefaultCodexHome
$CodexBin = Normalize-PathValue $(if ($CodexBin) { $CodexBin } else { Find-CodexBin }) ''
if (-not $AllowedRoots) {
  $AllowedRoots = @([Environment]::GetFolderPath('MyDocuments'), [Environment]::GetFolderPath('Desktop')) -join ';'
}
$AllowedRoots = Normalize-PathListValue (Read-Value 'Allowed folders (; separated)' $AllowedRoots -Required) $AllowedRoots

$lines = @(
  '# Generated by scripts/install-windows-bridge.ps1',
  "TICMIRO_SERVER_URL=$($ServerUrl.TrimEnd('/'))",
  "TICMIRO_AGENT_TOKEN=$AgentToken",
  "TICMIRO_BRIDGE_ID=$env:COMPUTERNAME-bridge",
  "CODEX_HOME=$CodexHome",
  "TICPROXY_BASE_URL=$($ServerUrl.TrimEnd('/'))/v1",
  "TICPROXY_API_KEY=$ProxyApiKey",
  "TICMIRO_ALLOWED_ROOTS=$AllowedRoots",
  "TICMIRO_LOCAL_ATTACHMENTS_DIR=$Root\runtime\attachments",
  "TICMIRO_CODEX_APP_SERVER_MODE=per-command",
  "TICMIRO_THREAD_SNAPSHOT_WAIT_MS=15000",
  "TICMIRO_THREAD_PROGRESS_SNAPSHOT_MS=3000"
)
if ($CodexBin) {
  $lines += "TICMIRO_CODEX_BIN=$CodexBin"
} else {
  Write-Warning "Codex CLI binary was not found. Install Codex Desktop/Codex CLI, then set TICMIRO_CODEX_BIN in $EnvFile if mobile thread send fails."
}
Set-Content -LiteralPath $EnvFile -Value ($lines -join "`r`n") -Encoding UTF8
Write-Output "Wrote $EnvFile"

try {
  $action = New-ScheduledTaskAction -Execute 'powershell.exe' -Argument "-NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File `"$StartScript`""
  $trigger = New-ScheduledTaskTrigger -AtLogOn
  $settings = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries -RestartCount 3 -RestartInterval (New-TimeSpan -Minutes 1)
  Register-ScheduledTask -TaskName $TaskName -Action $action -Trigger $trigger -Settings $settings -Description 'Polls the self-host Codex Mobile App server.' -Force | Out-Null
  if ($RunNow) { Start-ScheduledTask -TaskName $TaskName }
  Write-Output "Installed scheduled task: $TaskName"
} catch {
  Write-Warning "Scheduled Task install failed: $($_.Exception.Message)"
  $StartupDir = [Environment]::GetFolderPath('Startup')
  $Launcher = Join-Path $StartupDir 'Codex Mobile App Bridge.cmd'
  $content = "@echo off`r`nstart `"Codex Mobile App Bridge`" /min powershell.exe -NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File `"$StartScript`"`r`n"
  Set-Content -LiteralPath $Launcher -Value $content -Encoding ASCII
  if ($RunNow) {
    Start-Process -FilePath 'powershell.exe' -ArgumentList @('-NoProfile', '-ExecutionPolicy', 'Bypass', '-WindowStyle', 'Hidden', '-File', $StartScript) -WindowStyle Hidden
  }
  Write-Output "Installed startup launcher: $Launcher"
}
